### ISSUE TITLE
Language 9 – Chinese?

### ISSUE THREAD

**Issue by akulisch** [PaweX/Settlers_IV_Language_Translations#1]
The translation file s4_texts.dat9 is actually Chinese, also in the original game files (HE). How did you come to the conclusion that 9 is Danish? I did some reverse engineering myself and stumbled over some code that suggest the same.

Edit: Same with Italian (4), Norwegian (10), Spanish (3), and Swedish (8) which also seem to be Chinese.
Maybe those are the two variants Traditional and Simplified Chinese?
I know my way around some Japanese, but sadly cannot differentiate the two...

**Comment by akulisch** [comment]
Never mind all that – I was just too stupid for 2001 non Unicode encoded text files...

**Comment by akulisch** [comment]
Maybe we could enlist the corresponding used encodings for each of the translation files?

**Comment by PaweX** [comment]
@akulisch I've based on the original language files from the Gold Edition. Last time when I checked History Edition language files (year ago), they were also in the same language order. Chinese was number 7. For number 9 I have an original file with Danish translation.

> Maybe we could enlist the corresponding used encodings for each of the translation files?

I did some research some time ago, but not a deep one. I was only interested in languages that are missing. Most of these used European encoding. It is probably possible to add more languages but it will be a replacement for the existing ones, but only in some cases. If I remember correctly, it was possible to swap Hebrew (original translation) with Arabic (no translation) - for example. For standard encoding you can add many languages. Once I saw an uncoded part of Settlers IV code, it was a simple switch statement, for each language number there was a corresponding encoding. Everything after (if I remember well) number 18 was default encoding.
The list could be made, then it would be easier to tell which languages it is possible to add. However first, it would be nice to see any interest from S4 fans from countries that didn't have their S4 translation. If nobody is interested, then there is no point.
