### ISSUE TITLE
how to change language config

### ISSUE THREAD

**Issue by Holy-Shine** [PaweX/Settlers_IV_Language_Translations#3]
MiscData1.cfg:
![image](https://user-images.githubusercontent.com/14997709/182827767-1ce054b7-7ce1-44b5-973f-f06dfa9306ad.png)
how to change language config to own language fille

**Comment by Holy-Shine** [comment]
and where is chinese language file s4_texts.dat7
can I just create it by copying from s4_texts.dat0?

**Comment by PaweX** [comment]
Hi @Holy-Shine 
> how to change language config to own language fille

**For the History Edition:**
1. Go to _C: \Users \<your username>\Documents\TheSettlers4\Config_ and open the **GameSettings.cfg** file, eg with notepad.
2. Find the line Language = 0 (0 is English) and change it to Language = 7. This number is the language number, 7 is Chinese.
3. Save the file and run the game. Now the visible language in the game should be Chinese.

**For the old Gold Edition:**
just follow the above steps, but instead going to _C:\Users....._ find the **GameSettings.cfg** in the folder where the game is installed, in the _Config_ folder.

However, according to my present knowledge, nobody translated the game to Chinese yet. You can be the first. Just if you do any works, please upload it to the GitHub, and make a pull request to this project, even if you translate a bit as somebody else may continue. Thanks!

> and where is chinese language file s4_texts.dat7
> can I just create it by copying from s4_texts.dat0?

You could, but I advise you to not do it that way.
The best way to do it is: 
1. Download this template project file from the project ([link](https://github.com/PaweX/Settlers_IV_Language_Translations/blob/master/projects/TEMPLATE.s4_translation_project))
2. Open the **project file** in the _S4 Game Translation Tool_
3. Save it as **S4 Language file** by naming it "**s4_texts.dat7**"

The reason to do it this way is that when you work on a blank file, you can use the import option in the program (_Tools->Import Missing Texts_), then you (and others) will easily see which texts are not translated yet, and when you save the language file, only translated texts will be saved (without saving the English texts to the Chinese lang file - which would create some mess). If some texts in Chinese are missing, then the game will load them from English translation automatically (in the game only), so you don't need to be worried if you haven't translated some texts and leave them blank.

Hopefully all of this will help

**Comment by Holy-Shine** [comment]
Thanks for your detailed tutorials! I will try to translate it into Chinese if I have enouph idle time...

**Comment by Holy-Shine** [comment]
![image](https://user-images.githubusercontent.com/14997709/185603058-0271ce9d-3d4c-4256-9e8a-7ab1b95a7c17.png)
project file invalid....

**Comment by Holy-Shine** [comment]
![image](https://user-images.githubusercontent.com/14997709/185605251-b78c67d3-93cf-46d7-8778-6da74de8c9b5.png)
this is my

**Comment by PaweX** [comment]
> I will try to translate it into Chinese if I have enouph idle time...

Even if you do only partial translation (e.g. of short texts) that would be useful, I think.

**Comment by GitXarmoron** [comment]
> Thanks for your detailed tutorials! I will try to translate it into Chinese if I have enouph idle time...

如果还在研究Settlers_IV，可否加一下我微信25678002
